---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
spec:
  interval: 1h
  install:
    createNamespace: false
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    config:
      clients:
      - url: http://loki-gateway.loki/loki/api/v1/push
        tenant_id: 1
