---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
      interval: 1h
  values:
    serviceMonitor:
      enabled: true
    provider: cloudflare
    domainFilters:
    - chaosdorf.space
    env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: external-dns
          key: CF_API_TOKEN
