apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ping-exporter
spec:
  url: https://raw.githubusercontent.com/czerwonk/ping_exporter/master/dist/charts/
  interval: 1h
