apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ping-exporter
spec:
  releaseName: ping-exporter
  chart:
    spec:
      chart: ping-exporter
      sourceRef:
        kind: HelmRepository
        name: ping-exporter
  interval: 1h
  values:
    image:
      repository: czerwonk/ping_exporter
      tag: v1.0.0
