apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: snowflake
spec:
  interval: 1h
  install:
    createNamespace: false
  chart:
    spec:
      chart: tor-snowflake-proxy
      sourceRef:
        kind: HelmRepository
        name: snowflake
