apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  interval: 1h
  install:
    createNamespace: false
  chart:
    spec:
      chart: rook-ceph-cluster
      sourceRef:
        kind: HelmRepository
        name: rook-release
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    cephClusterSpec:
      dashboard:
        enabled: true
    ingress:
      dashboard:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        host:
          name: rook.chaosdorf.space
        tls:
        - secretName: rook-tls
          hosts:
            - rook.chaosdorf.space
