apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  interval: 1h
  install:
    createNamespace: false
  chart:
    spec:
      chart: rook-ceph-cluster
      sourceRef:
        kind: HelmRepository
        name: rook-release
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    cephClusterSpec:
      dashboard:
        enabled: true
      resources:
        mgr:
          requests:
            cpu: 50m
        mon:
          requests:
            cpu: 100m
        osd:
          requests:
            cpu: 100m
        prepareosd:
          requests:
            cpu: 50m
        mgr-sidecar:
          requests:
            cpu: 10m
        crashcollector:
          requests:
            cpu: 10m
        logcollector:
          requests:
            cpu: 10m
        cleanup:
          requests:
            cpu: 50m
        exporter:
          requests:
            cpu: 5m
    ingress:
      dashboard:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        host:
          name: rook.chaosdorf.space
        tls:
          - secretName: rook-tls
            hosts:
              - rook.chaosdorf.space
