apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: copyparty

spec:
  interval: 1h
  install:
    createNamespace: false

  chart:
    spec:
      chart: copyparty
      sourceRef:
        kind: HelmRepository
        name: copyparty

  values:
    ingress:
      enabled: true

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod

      hosts:
      - host: copyparty.chaosdorf.space
        paths:
        - path: /
          pathType: ImplementationSpecific

      tls:
      - hosts:
        - copyparty.chaosdorf.space
        secretName: ingress-tls

    command:
    - python3
    - /z/copyparty-sfx.py
    - '--no-crt'
    - '-c'
    - /z/initcfg
    - '-v'
    - /w::rwmd

    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 10m
        memory: 128Mi

    volume:
      volumeSpec:
        accessModes:
        - ReadWriteMany
        capacity:
          storage: 16Ti
        nfs:
          path: /srv/storage
          server: fileserver.chaosdorf.space

    persistence:
      volumeClaimSpec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
