apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kyverno
spec:
  interval: 1h
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
      interval: 1h
  values:
    admissionController:
      replicas: 3
    backgroundController:
      replicas: 3
    reportsController:
      replicas: 3
