{
 "title": "SNMP",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(sysUpTime, job)" } },
   {
    "name": "instance",
    "label": "Device",
    "query": {
     "query": "label_values(sysUpTime{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "label_values(ifIndex{job=~\"$job\",instance=~\"$instance\"}, ifAlias)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(sysUpTime{job=~\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "last reboot",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(time()*1000 - sysUpTime{job=~\"$job\",instance=\"$instance\"}*10)"
    }
   ]
  },
  {
   "title": "SNMP walk duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(snmp_scrape_walk_duration_seconds{job=~\"$job\",instance=\"$instance\"})    "
    }
   ]
  },
  {
   "title": "SNMP scrape PDUs returned",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(snmp_scrape_pdus_returned{job=~\"$job\",instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Interface $interface",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "interface",
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bps", "label": "in (-) / out (+)" }
   ],
   "targets": [
    {
     "expr": "8*irate(ifOutOctets{job=~\"$job\",instance=\"$instance\",ifAlias=~\"$interface\"}[5m])",
     "legendFormat": "out"
    },
    {
     "expr": "8*irate(ifInOctets{job=~\"$job\",instance=\"$instance\",ifAlias=~\"$interface\"}[5m])",
     "legendFormat": "in"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "pps", "label": "in (-) / out (+)" }
   ],
   "targets": [
    {
     "expr": "irate(ifOutUcastPkts{job=~\"$job\",instance=\"$instance\",ifAlias=~\"$interface\"}[5m])",
     "legendFormat": "Unicast out"
    },
    {
     "expr": "irate(ifInUcastPkts{job=~\"$job\",instance=\"$instance\",ifAlias=~\"$interface\"}[5m])",
     "legendFormat": "Unicast in"
    },
    {
     "expr": "irate(ifOutBroadcastPkts{job=~\"$job\",instance=\"$instance\",ifAlias=~\"$interface\"}[5m])",
     "legendFormat": "Broadcast out"
    },
    {
     "expr": "irate(ifInBroadcastPkts{job=~\"$job\",instance=\"$instance\",ifAlias=~\"$interface\"}[5m])",
     "legendFormat": "Broadcast in"
    },
    {
     "expr": "irate(ifOutMulticastPkts{job=~\"$job\",instance=\"$instance\",ifAlias=~\"$interface\"}[5m])",
     "legendFormat": "Multicast out"
    },
    {
     "expr": "irate(ifInMulticastPkts{job=~\"$job\",instance=\"$instance\",ifAlias=~\"$interface\"}[5m])",
     "legendFormat": "Multicast in"
    },
    {
     "expr": "irate(ifOutDiscards{job=~\"$job\",instance=\"$instance\",ifAlias=~\"$interface\"}[5m])",
     "legendFormat": "Discards out"
    },
    {
     "expr": "irate(ifInDiscards{job=~\"$job\",instance=\"$instance\",ifAlias=~\"$interface\"}[5m])",
     "legendFormat": "Discards in"
    },
    {
     "expr": "irate(ifOutErrors{job=~\"$job\",instance=\"$instance\",ifAlias=~\"$interface\"}[5m])",
     "legendFormat": "Errors out"
    },
    {
     "expr": "irate(ifInErrors{job=~\"$job\",instance=\"$instance\",ifAlias=~\"$interface\"}[5m])",
     "legendFormat": "Errors in"
    }
   ]
  }
 ]
}