apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus-snmp-exporter
spec:
  interval: 1h
  install:
    createNamespace: false
  chart:
    spec:
      chart: prometheus-snmp-exporter
      sourceRef:
        kind: HelmRepository
        name: prometheus-snmp-exporter
  values:
    serviceMonitor:
      enabled: true
      namespace: prometheus-snmp-exporter
      module:
        - if_mib
      honorLabels: true
      params:
        - name: cr1
          target: 10.0.0.1
          module:
            - if_mib
