{
 "title": "Octoprint",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DATASOURCE", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Cancelled Prints",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "octoprint_cancelled_prints_total"
    }
   ]
  },
  {
   "title": "Total Prints",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "octoprint_done_prints_total" }
   ]
  },
  {
   "title": "Failed Prints",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    { "expr": "octoprint_failed_prints_total" }
   ]
  },
  {
   "title": "Print progress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "octoprint_print_progress", "legendFormat": "{{path}}" }
   ]
  },
  {
   "title": "State",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "targets": [
    { "expr": "octoprint_printer_state_info{}", "legendFormat": "{{state_id}}" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "octoprint_temperatures_target", "legendFormat": "target {{identifier}}" },
    { "expr": "octoprint_temperatures_actual", "legendFormat": "actual {{identifier}}" }
   ]
  }
 ]
}