apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: octoprint
resources:
  - endpoints.yaml
  - ingress.yaml
  - namespace.yaml
  - service.yaml
  - servicemonitor.yaml
configMapGenerator:
  - name: dashboard
    files:
      - dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "true"
