{
 "title": "FreePBX Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Calls",
   "type": "stat",
   "description": "Count of calls currently running",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(asterisk_calls_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Call Sum Counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(asterisk_calls_sum)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SIP Trunk Connections",
   "type": "stat",
   "description": "Incoming/Outgoing connections for SIP trunks.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(asterisk_endpoints_channels_count{id=\"PJSIP/EPVPN\"})",
     "legendFormat": "EPVPN"
    },
    {
     "expr": "sum(asterisk_endpoints_channels_count{id=\"PJSIP/Easterhegg\"})",
     "legendFormat": "Easterhegg"
    }
   ]
  },
  {
   "title": "Channels, Endpoints, Bridges",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(asterisk_channels_count)", "legendFormat": "Channels" },
    { "expr": "max(asterisk_endpoints_count)", "legendFormat": "Endpoints" },
    { "expr": "max(asterisk_bridges_count)", "legendFormat": "Bridges" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(asterisk_core_uptime_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Reload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(asterisk_core_last_reload_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Asterisk Endpoints",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by(id) (asterisk_endpoints_state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SIP Trunk Registration Status",
   "type": "table",
   "description": "List of SIP trunks and their registration status.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "max by(username) (asterisk_pjsip_outbound_registration_status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}