apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbox
spec:
  interval: 1h
  install:
    createNamespace: false
  chart:
    spec:
      chart: netbox
      sourceRef:
        kind: HelmRepository
        name: chaosdorf
  values:
    image:
      repository: quay.io/chaosdorf/netbox
    plugins:
      - netbox_secretstore
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
      - host: netbox-beta.chaosdorf.space
        paths:
        - /
      tls:
      - secretName: netbox-tls
        hosts:
        - netbox-beta.chaosdorf.space
