---
apiVersion: v1
kind: Secret
metadata:
  name: passwords
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: db_password,email_password,napalm_password,redis_tasks_password,redis_cache_password,secret_key
