---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ariang

spec:
  interval: 1h
  install:
    createNamespace: false

  chart:
    spec:
      chart: ariang
      sourceRef:
        kind: HelmRepository
        name: ariang

  values:
    ingress:
      enabled: true

      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod

      hosts:
        - host: aria.chaosdorf.space
          paths:
            - path: /
              pathType: ImplementationSpecific

      tls:
        - hosts:
          - aria.chaosdorf.space
          secretName: ingress-tls

    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 256Mi

    volume:
      volumeSpec:
        accessModes:
          - ReadWriteOnce
        capacity:
          storage: 16Ti
        nfs:
          path: /srv/storage/tmp
          server: fileserver.chaosdorf.space

    persistence:
      volumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi