apiVersion: v1
kind: PersistentVolume
metadata:
  name: samba-adapter-data
  labels:
    app: samba-adapter
    volume: data
spec:
  capacity:
    storage: 16Ti
  nfs:
    server: fileserver.chaosdorf.space
    path: /srv/storage
  accessModes:
    - ReadWriteOnce
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-adapter-data
  labels:
    app: samba-adapter
    volume: data
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: samba-adapter
      volume: data
  resources:
    requests:
      storage: 16Ti
  volumeName: samba-adapter-data
  storageClassName: ''
  volumeMode: Filesystem
