apiVersion: "kyverno.io/v1"
kind: "ClusterPolicy"
metadata:
  name: "enforce-replicas"
spec:
  background: true
  rules:
  - name: "set-replicas"
    match:
      resources:
        kinds:
        - "Deployment"
    mutate:
      patchStrategicMerge:
        spec:
          replicas: 3

