apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 1h
  install:
    createNamespace: false
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    serviceMonitor:
      enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        traefik.ingress.kubernetes.io/router.entrypoints: websecure,web
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
      - grafana.chaosdorf.space
      tls:
      - secretName: grafana-tls
        hosts:
        - grafana.chaosdorf.space
    grafana.ini:
      auth.anonymous:
        enabled: true
        org_name: Main Org.
        org_role: Editor
      auth:
        disable_login_form: true
      users:
        default_theme: system
    sidecar:
      dashboards:
        enabled: true
        provider:
          disableDelete: true
        searchNamespace: ALL
      datasources:
        enabled: true
        searchNamespace: ALL
    plugins:
      - grafana-mqtt-datasource
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: default
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: false
          options:
            path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        node-exporter-full:
          gnetId: 1860
          revision: 37
          datasource: Prometheus
