---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
  - dashboards.yaml
  - datasource.yaml
  - helm-release.yaml
  - helm-repository.yaml
  - namespace.yaml
